.TH "/home/lucio/Documentos/desenvolvimento/algoritmo_C/bibliotecas/static/libEdm/includes Directory Reference" 3 "Sat Apr 15 2017" "Version 1.0.00" "Library EDM" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/home/lucio/Documentos/desenvolvimento/algoritmo_C/bibliotecas/static/libEdm/includes Directory Reference \- 
.SH SYNOPSIS
.br
.PP
.SS "Files"

.in +1c
.ti -1c
.RI "file \fBedm\&.h\fP"
.br
.RI "\fIFile containing includes, defines, and demias externados\&. \fP"
.in -1c
